# Usa una imagen de Java como base (aquí usamos OpenJDK 11, ajústalo según tu versión de Java)
FROM openjdk:11-jdk-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia todo el contenido de tu proyecto al directorio de trabajo del contenedor
COPY . .

# Navega al directorio donde está tu clase principal
WORKDIR /app/src/main/java

# Compila tu aplicación (ajusta el nombre de los paquetes si es necesario)
RUN javac Service/Broker/TestMain.java

# Especifica el puerto en el que tu aplicación escuchará (ajústalo si tu aplicación usa otro puerto)
EXPOSE 8080

# Ejecuta la clase principal
CMD ["java", "Service.Broker.TestMain"]
